import re 
with open("File_name.txt","r") as f:
        for line in f:
            line = line.replace(",", " ")
            line = line.replace(";", " ")
            line = line.replace(".", " ")
            line = line.replace("!", " ")
            line = line.replace("//", " ")
            line = line.replace("|", " ")
            line = line.replace("*", " ")
            line = line.replace("(", " ")
            line = line.replace("[)]", " ")
            line = line.replace("[", " ")
            line = line.replace("]", " ")
            line = line.replace("=", " ")
            line = line.replace("/", " ")
            line = line.replace("", "")
            line = line.replace("%", " ")
            line = line.replace('"', " ")
            line = line.replace('"', " ")
            line = line.replace(",", " ")
            line = line.replace("?", " ")
            line = line.replace(";", " ")
            line = line.replace(".", " ")
            line = line.replace("!", " ")
            line = line.replace("&amp", "")
            line = line.replace("&", "")
            line = line.replace("//", " ")
            line = line.replace("-", " ")
            line = line.replace("'"," ")
            line = line.replace(")", " ")
